name: Remote Download
on: [workflow_dispatch]
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download File
        run: curl -L "https://dl.google.com/antigravity/antigravity-win-x64.exe" -o setup.exe
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: setup.exe
